config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'welcome#root'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get 'auth/:provider/callback', to: 'sessions#googleAuth'
  get 'auth/failure' => 'welcome#root'
  get '/auth_login' => 'welcome#auth_login'
  get '/logout' => 'sessions#destroy'
  delete '/logout' => 'sessions#destroy'
  
  get '/best_host' => 'welcome#best_host'
  
  resources :guests do
    resources :invites
  end

  resources :parties do
    resources :invites
  end

  resources :hosts do
    resources :parties
  end

  resources :accounts, only: [:new, :create]
  resources :parties
  resources :invites
  
  
end

app/models/invite.rb
class Invite < ApplicationRecord
    belongs_to :party
    belongs_to :guest

    validates :add_on, :rsvp, presence: true
    
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  before_action :find_invite, only: [:show, :edit, :update, :destroy]
  
  def new
    @invite = Invite.new
    @party_id = params[:party_id]
  end

  def create
    @party = Party.find(params[:party_id])
    @invite = Invite.new(invite_params)
    @invite.guest = current_user
    @invite.party = @party
    if @invite.save
       redirect_to guest_path(current_user)
    else
      @party_id= params[:party_id]
      render :new
    end
  end

  def index
    if params[:guest_id]
      @invites = Guest.find(params[:guest_id]).invites
    else
      @invites = Invite.all
    end
  end

  def show
  
  end

  def edit
    if authorized_guest
      render :edit
    else
      flash[:danger] = "You are not an authorized user."
      redirect_to parties_path
    end
  end

  def update
    if authorized_guest
      @invite.update(invite_params)
      redirect_to guest_path(current_user)
    else
      flash[:danger] = "You are not an authorized user."
      redirect_to parties_path
    end
  end

  def destroy
    if authorized_guest
      @invite.destroy
      redirect_to guest_path(current_user)
    else
      flash[:danger] = "You are not an authorized user."
      redirect_to guest_path(current_user)
    end
  end

  private

  def invite_params
    params.require(:invite).permit(:add_on, :rsvp, :guest)
  end

  def find_invite
    @invite = Invite.find(params[:id])
  end

  def authorized_guest
    current_user == @invite.guest
  end

end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/views/invites/edit.html.erb
<h1>Edit this Invite</h1>

<br>
<%= render 'partials/invite' %>

app/views/invites/index.html.erb
<h2>Invite List</h2>

<% @invites.each do |invite| %>
<div>
    <ul>
      <li><p><%= link_to "#{invite.party.name}", guest_invite_path(invite.guest, invite) %> 
      - <%= invite.party.description %> 
      - Hosted by : <%= link_to "#{invite.party.host.name}", host_path(invite.party.host) %></p></li>
    </ul>
  </div>
<% end %>

app/views/invites/new.html.erb
<h1>Join this Party!</h1>
<p>Choose the options below to complete the process.</p>

<br>
<%= render 'partials/invite' %>

app/views/invites/show.html.erb
<h2>My Party</h2>
<div class="boxed">
Party Name : <%= @invite.party.name %><br>
Description : <%= @invite.party.description %><br>
Location : <%= @invite.party.location %><br>
Date & Time : <%= @invite.party.strf_time %><br>
Dress Code<%= @invite.party.dress_code %><br>
How many people am I bringing with? : <%= @invite.add_on %><br>
RSVP status : <%= @invite.rsvp %><br>

  <% if user_type == "Guest" && @invite.guest == current_user && @invite != nil %>
      <%= link_to "Edit this invite", edit_guest_invite_path(current_user, @invite) %>
  <% end %>

  <% if user_type == "Guest" && @invite.guest == current_user %>
      <%= form_tag guest_invite_path(@invite.guest, @invite.id), method: "delete" do %>
        <%= submit_tag "Delete Party" %>
      <% end %>
  <% end %>
</div>