config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'welcome#root'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get 'auth/:provider/callback', to: 'sessions#googleAuth'
  get 'auth/failure' => 'welcome#root'
  get '/auth_login' => 'welcome#auth_login'
  get '/logout' => 'sessions#destroy'
  delete '/logout' => 'sessions#destroy'
  
  get '/best_host' => 'welcome#best_host'
  
  resources :guests do
    resources :invites
  end

  resources :parties do
    resources :invites
  end

  resources :hosts do
    resources :parties
  end

  resources :accounts, only: [:new, :create]
  resources :parties
  resources :invites
  
  
end

app/models/party.rb
class Party < ApplicationRecord
    belongs_to :host
    has_many :invites
    has_many :guests, through: :invites

    validates :name, :description, :location, :date_time, presence: true

    def strf_time
        date_time.strftime("%d %b %Y %l:%M %p")
    end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
 before_action :verify_accountable
 before_action :find_party, :party_host, only: [:edit, :update, :destroy]
 
  def index
    @parties = Party.all
  end

  def new
    host?
    if params[:host_id]
      find_host
    end
    @party = Party.new
  end

  def create
    host?
    @party = Party.new(party_params)
    if params[:host_id]
      find_host
      @party.host = @host
    end
  
    if @party.save
      redirect_to host_party_path(@party.host, @party)
    else
      render :new
    end
  end

  def show
    find_party
  end

  def edit
    if authorized_host
      render :edit
    else
      flash[:danger] = "You are not an authorized user."
      redirect_to party_path(@party)
    end
  end

  def update
    if authorized_host
      @party.update(party_params)
      redirect_to host_party_path(@party.host, @party)
    else
      flash[:danger] = "You are not an authorized user."
      redirect_to parties_path
    end
  end

  def destroy
    @host = @party.host
    if authorized_host
      @party.destroy
      redirect_to host_path(current_user)
    else
      flash[:danger] = "You are not an authorized user."
      redirect_to parties_path
    end
  end

  private

  def party_params
    params.require(:party).permit(:name, :description, :location, :date_time, :dress_code, :host_id)
  end

  def find_party
    @party = Party.find(params[:id])
  end

  def find_host
    @host = Host.find(params[:host_id])
  end

  def party_host
    if params[:host_id]
      find_host
      @party.host = @host
    end
  end

  def authorized_host
    current_user == @host
  end

end

app/helpers/parties_helper.rb
module PartiesHelper

end

app/views/parties/edit.html.erb
<h1>Edit this Party</h1>
<%= render 'partials/party' %>

app/views/parties/index.html.erb
<h2>Party list</h2>

<% if user_type == "Host" %>
  <%= link_to "My Page", host_path(current_user.id) %>
<% end %>

<% if user_type == "Host" %>
  <%= link_to "Create a new party", new_host_party_path(current_user.id) %>
<% end %>

<% if user_type == "Guest" %>
  <%= link_to "My Page", guest_path(current_user.id) %>
<% end %>

<% @parties.each do |party| %>
<div class="boxed">
  <ul>
    <li>Party Name: <%= link_to "#{party.name}", party_path(party.id) %></li>
    <li>Description: <%= party.description %></li>
    <li>Location: <%= party.location %></li>
    <li>Date & Time: <%= party.strf_time %></li>
    <li>Dress Code: <%= party.dress_code %></li>
    <li>Hosted by: <%= link_to "#{party.host.name}", host_path(party.host.id) %></li>
  </ul>
</div>
<% end %>

app/views/parties/new.html.erb
<h1>Create a new Party</h1>
<%= render 'partials/party' %>

app/views/parties/show.html.erb
<div class="boxed">
<ul>
  <li>Party Name: <%= @party.name %></li>
  <li>Description: <%= @party.description %></li>
  <li>Location: <%= @party.location %></li>
  <li>Date & Time: <%= @party.strf_time %></li>
  <li>Dress Code: <%= @party.dress_code %></li>
  <li>Hosted by: <%= @party.host.name %></li>
<ul>
</div>

<%= link_to "Back to Party List", parties_path %>

<% if user_type == "Host" && @party.host == current_user && @party != nil %>
  <%= link_to "Edit Party", edit_host_party_path(current_user, @party) %>
<% end %>

<% if user_type == "Host" && @party.host == current_user && @party != nil %>
  <%= form_tag party_path(@party), method: "delete" do %>
    <%= submit_tag "Delete Party" %>
  <% end %>
<% end %>

<% if user_type == "Guest" && !@party.guests.include?(current_user) %>
  <%= link_to "Join this party!", new_party_invite_path(@party) %>
<% end %>