config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'welcome#root'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get 'auth/:provider/callback', to: 'sessions#googleAuth'
  get 'auth/failure' => 'welcome#root'
  get '/auth_login' => 'welcome#auth_login'
  get '/logout' => 'sessions#destroy'
  delete '/logout' => 'sessions#destroy'
  
  get '/best_host' => 'welcome#best_host'
  
  resources :guests do
    resources :invites
  end

  resources :parties do
    resources :invites
  end

  resources :hosts do
    resources :parties
  end

  resources :accounts, only: [:new, :create]
  resources :parties
  resources :invites
  
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def root
        @parties = Party.all
    end

    def best_host
        @host_id = Host.has_most_parties
        @host = Host.find_by(id: @host_id)
    end
end

app/views/welcome/auth_login.html.erb
<%= link_to "Log in as a host", new_host_path %>
<%= link_to "Log in as a guest", new_guest_path %> 

app/views/welcome/best_host.html.erb
<h2>Best Host</h2>

<h3><%= @host.name %></h3><br>
<% @host.parties.each do |party| %>
  <ul>
    <li><%= link_to "#{party.name}", party_path(party) %></li>
  </ul>
<% end %> 

app/views/welcome/root.html.erb
<% if !logged_in? %>
  <h1>Welcome to Party Planner!</h1>
  <h3>Sign up or Log In</h3>
<% end %>

<% if logged_in? %>

<% if user_type == "Host" %>
  <%= link_to "My Page", host_path(current_user.id) %>
<% end %>

<% if user_type == "Guest" %>
  <%= link_to "My Page", guest_path(current_user.id) %>
<% end %>

<%= link_to "Check out the host who has most parties", best_host_path %>

  <% @parties.each do |party| %>
  <div class="boxed">
    <ul>
      <li>Party Name: <%= link_to "#{party.name}", party_path(party.id) %></li>
      <li>Description: <%= party.description %></li>
      <li>Location: <%= party.location %></li>
      <li>Date & Time: <%= party.date_time %></li>
      <li>Dress Code: <%= party.dress_code %></li>
      <li>Hosted by: <%= link_to "#{party.host.name}", host_path(party.host.id) %></li>
    </ul>
  </div>
  <% end %>
<% end %>